#+title:      Aquinas on creation
#+date:       [2023-04-21 Fri 12:10]
#+filetags:   :theology:aquinas:
#+identifier: 20230421T121021

* Aquinas' interpreation of creation

Taken from: Barron, Robert. Thomas Aquinas: Spiritual Master. Crossroad Publishing Company, 2008.

** Creation: the nothing that is everything

 [Ch.3, p.114]

 ... Thomas interprets creation--the fundamental rapport between God and the
 word--in light of the experience of Jesus Christ. This means, basically, that
 the world--in all of its particularity and peculiarity, and in each of its
 nooks and crannies--is filled, every moment and in the most intimate way
 possible, with the sustaining presence of God. The universe is constantly held
 up by, and suffused with, the creating power of the ground of being. At every
 instant, God brings the world from nonbeing into being, illuminating it as the
 sun illumines the sky.  This divine "shining" is creation, and allowing oneself
 to be "shone through" is to be a creature.
