#+title:      philology-defn
#+date:       [2023-04-03 Mon 09:42]
#+filetags:   :philology:
#+identifier: 20230403T094250

[[file:~/Desktop/Drews Desk Top/philology/1997-mackay.c-philology.org::*Historical Development Of Classical Philology]]

Note: This is rather an old definition. For a more recent discussion, see
Turner, James. /Philology: The forgotten origins of the modern humanities./
Princeton University Press, 2015.

* Philology

Classical philology and philology are kindred but not the same. Philology in the
general sense derives from the historical development of Classical
philology. Accordingly, to understand philology one has to examine it in the
context of the historical development of Classical philology.

** What Is Classical Philology?

One definition of modern Classical philology:

#+BEGIN_QUOTE
"Classical philology is the science which concerns itself with everything that
has been transmitted from antiquity in the Greek or Latin language. The object
of this science is thus the Greco-Roman, or Classical, world to the extent that
it has left behind monuments in a linguistic form." (J. and K. Kramer, La
filologia classica [1979] 1)
#+END_QUOTE

This definition therefore clearly excludes archaeology. Furthermore, it excludes
the study of history, though to the extent that history uses linguistic
documents it must avail itself of the methods and techniques of philology. This
is particularly true of ancient history, which consists mainly in the
examination of information of a linguistic nature. An attempt in Germany to make
the study of antiquity more broadly based was described with the term
Altertumswissenschaft (which sometimes appears in French in the form science de
l'antiquité). This, then, is the nineteenth century version of
interdisciplinarity. Nihil novum sub sole! English has developed no such
concept, though the term "Classical studies" is sometimes used to include more
than just textual studies.

** Historical Development Of Classical Philology

Modern Classical philolgy begins in the early Renaissance with Petrarch
(1304-74). Petrarch was very unhappy with his contemporary world, and saw in the
world of Roman antiquity as it was known to him through the texts of surviving
Latin authors an image of a superior civilization. (Famously he said in his
autobiographical sketch incubui unice inter multa ad notitiam vetustatis quoniam
mihi semper aetas ista displicuit [I uniquely strove in the midst of many
activities toward a knowledge of antiquity, since this age always displeased
me]). This was an effort to improve the Christian world through the examination
of the moral precepts of the ancients. Specifically he referred once to his
interests as studia humanitatis, studies of humanity. Humanitas is literally
"humanness" and is the word used by the Romans to describe civilized, cultured
life: civilization is what distinguishes mankind from the beasts, and so that
civilized life that which describes mankind in a normative sense. Petrarch used
this expression once, but it was quickly picked up by those who carried on his
interests, the humanists of the Renaissance.  The term humanism is often used to
describe the frame of mind characteristic of the Renaissance. This term is a
nineteenth century coinage. At the time people who investigated Classical
antiquity were called humanists, and the kindred sense humanity continues today
in the phrase "the humanities." The study of Classical "humanity" was at the
time often contrasted with a purely theological consideration of Christianity,
which was called divinity. This contrast has led to the obnoxious modern
expression "saecular humanism," which really means "atheistic materialism,"
something quite different from the humanism of the Renaissance.

The fundamental opposition of "humanism" was to the formalistic scholasticism of
the later Middle Ages. This was a complicated system of self-supporting logical
constructs that defended the theological interpretations of Chistianity made by
the medieval church. This system was based fundamentally on a belief in the
supreme and stern god's dissatisfaction with an inherently corrupt and
irredemable mankind. Only the mercy of god could save mankind from its
squalor. Humanism was more optimistic, believing that the study of Classical
antiquity could, when combined with the correctly understood teachings of the
Church, lead to an improvement both in the saecular world and in the Christian
life of the individual. The evil of the world is ascribed not to original sin or
predestination but to ignorance. Dispel the shadows of ignorance and the world
will improve.

So what does this have to do with philology? The works of Classical antiquity
were preserved in manuscripts usually writen many centuries after the original
composition. Accordingly, one of the first steps of using antiquity to improve
the world is to determine a correct text of what the ancients said. This led to
a search in religious institutions for better texts of preserved authors and for
the discovery of works not yet known to have survived from antiquty. In
addition, there was the need to establish the correct version of the ancient
works. At the same time, men writing in Latin, the language of education,
attempted to purify the language, returning to the idiom of antiquity
(esp. Cicero) and suppressing the "barbarous" usages of medieval Latin (which
diverged from Classical idiom because of both the interference of the native
languages of the writers of Latin and the influence of the style of the Latin
Vulgate bible (written in a lower-class Latin it also labors under the
difficulty of being an overly literal translation of the Greek). This desire to
return to Classical idiom resulted in two very characteristic traits of
Classical philology: the careful examination of the usage of individual words
and the writing of line-by-line commentaries on ancient works, often
concentrating on the explanation of words through the citation of parallels
(examples of other usages adduced to illuminate the sense in the passage under
discussion).

** The Meaning Of Philology

It is this method of procedure that leads to the use of the word
philology. Philology (philologia) is the abstraction of the Greek word
philologue (philologos). A philologos is "one to whom the word is dear" and the
word signified in antiquity a commentator on the ancient poetical texts like the
Iliad, which contained numerous words whose significance was obscure. It is this
specific aspect of Classical philology that carries over into the general sense
of "philology." Classical philology has developed a whole panoply of tools
designed specifically for the circumstances of the preservation of ancient
texts. For example, codicology is the study of the physical aspect of medieval
manuscripts, paleogrpahy is the study of various systems of writing, papyrology
is the study of ancient texts preserved on papyrus. Philology is fundamentally
"the correct interpretation of texts."

The very concept of philology is under attack through various theories,
generally of a French origin. One thinks of people like Barthes, Derrrida,
Lacan. These theories deny any fixed meaning to the text, any authorial intent,
any "autonomy" of the text-in short any objective meaning to the text. Now it is
true that there are ambiguities in words, and correct philology takes this into
account. Nonetheless, it is illogical toconclude that because absolute,
objectively demonstrable certainty as to the meaning of a word is impossible, no
certainty is possible. The argument itself is self-defeating. If there is no
fixed meaning to words, then the very texts that explain this idea are
themselves devoid of meaning. It's like trying to make someone accept a check
written against a bank that you assert is insolvent. All attempts to undercut
traditional philology are pernicious attempts to undermine the belief in a
recoverable sense of the text, the upshot being that the "critic" can impose on
the text whatever meaning he feels like.

** Relevance Of Philology To History

From Conrad Russel, /The Crisis of Parliaments/. English History 1509-1660 (1971)
1:

#+BEGIN_QUOTE
"Historians may learn much from the students of art, architecture, or
archaeology. Nevertheless, history is essentially the study of the past by means
of written records."
#+END_QUOTE

Though not everyone would agree with this statement, it is fundamentally
true. True history is only possible for periods when there are written
records. Physical evidence can supplement it, and allows for various inferences
in the pre-historic period. Nonetheless, most history involves the use of
written records, and the difficulties inherent in interpreting purely physical
evidence should be clear to anyone interpreting pre-historic
archaeology. Philology is crucial to interpreting all written evidence.

** The Practice Of Philology

What then does the philological method signify in practice? It is the rigorous
effort to attempt to recover the sense of the passage in question through the
detailed examination of the language in context. First one examines the words of
the text. What do they signify? This can only be determined by a nuanced
examination of other uses of the words. How are they used else in the authors
own work? In contemporary writing? Is there a shift in meaning that develops
over time? Dictionaries are of course an indispensable aid in this effort, but a
dictionary is simply someone else's attempt to digest the sense of a word. They
may not have noticed idioms relative to the present case, and in any case have
no objective determining authority. An examination of the citations given is
usually necessary.  The words themselves must be interpreted in context. Context
here means several different things. How does this passage fit into the
immediate argument in the text and in the broader sense of the work as a whole?
How does it fit into the author's overall ideas as they can be recovered from
the corpus of the work. At times one has to broaden the context to consider a
question like, How does the meaning here fit into the genre in which the author
is writing or into overall context of ancient thought?

A necessary accompaniment of the correct interpretation of the text is not only
an examination of the meaning of the words used but of the syntax of the
sentences in which they are found. This is not the place to go into the methods
of understanding the syntax of a language. The internal comparative method again
is prominent. In any case, any number of misunderstandings of texts results from
a defective understanding of the grammar in question, and sound understanding of
the language can often make it clear what can and cannot be meant.

Philology is thus not a fixed procedure comparable to the methodology of the
physical sciences. Instead, it is the use of human reason to attempt to
understand, through the examination of comparative linguistic evidence, the
correct, "intended" meaning of a text. Obviously there are times when either
ambiguity was intended from the start by the author or because of our limited
knowledge of antiquity (or the middle ages) cannot now be fully resolved. This
is particularly true of works of fiction. Nonetheless, in the overwhelming
majority of instances, philology is a way to reach an understanding both of what
a text can and of what it cannot mean. It is not a fixed methodology, but more a
frame of mind. Careful and rigorous attention to the sense of a text as it can
be deteremined on the basis of both external and internal criteria is the
essence of philology. A scholar properly trained in the methods of philology has
the ability to reign supreme in the battlefield of interpreting linguistic
evidence

** Philology In Action

*** The Donation of Constantine

The use of this methology to examine historical documents goes back to the
Renaissance. A noteworthy example of this is the pamphlet /Declamatio de falso
credita et ementita Constantini Donatione/ (Discourse on the wrongly believed and
falsified Grant of Constantine), written by the Italian humanist Lorenzo Valla
(1407-57). The Donatio Constantini was a document purported to record the grant
by the first Christian emperor of various privileges to the pope. This document
had already been attacked by an older contemporary of Valla, Nicholas of
Cusa. That attack was grounded on argumentation based on ecclesiastic history
and theology. Such a method is not philological. It is basically historical. The
document in question cannot be legitimate because the evidence of other texts
and external considerations (e.g., at some intervening period the situation
called for by the grant did not prevail, hence the grant did not exist at that
time). Valla used two arguments. First, he examined the earliest manuscripts of
the Decreta of the church and found that the Donation was not present in
them. Hence, it was a later interpolation. Second, he demonstrated that the
language used in the document was a debased form of Latin that could not have
been used in the time of Constantine and could only have been written during the
middle ages. In rather immoderate language he referred to the author as "this
ass who screeches so horribly and monstrously" (huic asino tam vaste
immaniterque rudenti) and referred to the language as "the speech of some stupid
little churchman [who was] bloated and thick-headed and during a hangover puked
out these sentences and words (oratio ... alicuius clericuli stolidi... saginati
et crassi ac inter crapulam interque fervorem vini has sententias et haec verba
ructantis)." The violence of the language reflects the impatience of one who
understands philology that some should have thought that such a composition
would fool posterity.

** Erasmus And The New Testament

During the time of Erasmus just before and at the start of the Reformation, the
new philological method was applied to the editing and interpretation of the
bible. This was a novel and disquieting procedure. Previously, the Latin text
had been interpreted in light of the usages of the medieval church, and a number
of words were interpreted on the assumption that they reflected the meaning
given to these words in the technical language of the church. Erasmus first
demonstrated that the text used in the accepted version of the Vulgate was not
actually the original version. Furthermore, he not only showed that even the
corrected Latin version was often misleading when compared to the original, but
attempted to show that the sense of the words with medieval meanings was often
rather different when they were interpreted in the context of the contemporary
language of Greco-Roman antiquity. In the various prefaces of his text of the
New Testament he had to defend himself against those who belittled his
grammatical endeavors and wished to preserved the traditional text, regardless
of any arguments about its validity. He said, "Why trouble about punctuation?
Because such a trivial matter as incorrect punction produces a heretical sense
(tantula res gignit hereticum sensum)". Regardless of the theological
implications, what he means is that it is only on the basis of a sound
philological understanding of a text that it can be properly interpreted.

** The Goal Of Philology

Philology is not an end in itself. It is the primary prerequisite to
understanding texts and thus it makes possible the further interpretation and
utilization of such texts on the basis of this understanding.

The ultimate goal of philology is clearly expressed by the great Milman Parry:

#+BEGIN_QUOTE
The literature of every country and of every time is understood as it ought to
be only by the author and his contemporaries. Between him and them there exists
a common stock of experience which enables the author to mention an object or to
express an idea with the certainty that his audience will imagine the same
object and will grasp the subtleties of his idea... The task, therefore, of one
who lives in another age and wants to appreciate that work correctly consists
precisely in recovering the varied information and the complexes of ideas which
the author assumed to be the natural property of his audience." (The Making of
Homeric Verse [1971] 2).
#+END_QUOTE

Parry goes on to say that "What I have just said is obviously no more than one
of the countless ways of expressing a great truth of scholarship." Perhaps it
was obvious in 1928, but it no longer is today when much of scholarship attempts
to impose upon the past modern preconceptions that have nothing to do with the
thoughts and ideas of the past. Philology is the vehicle by which one attempts
to arrive at the understanding of the past outlined by Parry.

** Bibliography

There is no single place (as far as I know) to find a clear and succinct
presentation of the general principles of philology. The word continues to be
used in the context of studying modern foreign languages, but since the
methodology delineated here is generally denigrated in such circles, I don't
know what it signifies there. For a general introduction to the development of
Classcial philology, the following works are useful:

  - Rudolf Pfeiffer, History of Classical Scholarship From 1300 to 1850 (1976)
  - L.D. Reynolds and N.G. Wilson, Scribes and Scholars (1968)

For the adventurous souls who want to learn about Classical philology in great detail:

  J.E. Sandys, A History of Classical Scholarship (1903)
