#+title:      Truth and Relativism DeMarco
#+date:       [2023-09-26 Tue 10:46]
#+filetags:   :philosophy:theology:
#+identifier: 20230926T104614

* Rough notes on DeMarco--Truth and Relativism

** Truth and tolerance

*Definitions:*
  - *Truth* (philosophy) describes how things are, what=t something is.
  - *Tolerance* (politics) describes how people in a civil society behave towards
    one another.

*Truth now treated as opinion:*
In today's society and culture, tolerance is valued so much higher than truth
that the latter is now treated as mere opinion, truth is essentially hidden.

Society needs to recover its estimation of philosophy so that ideas, such as
truth and tolerance, are in their proper order (Aquinas) and relation to one
another.

*Relativism:* Society and culture have adopted /relativism/ to deal with the problem
in our /pluralistic society/, that stating truth would make some idea, and those
espousing them, superior than others. In Joseph Ratzinger's opinion relativism
poses "the most profound difficulty of our day."

Society's attitude towards the Catholic Church stems from the Church's supposed
intolerance. But the Church is opposed to tolerance herself, she simply does not
hold tolerance equal to, or higher, than truth. The Church does not recognise
"your truth" and "my truth", she recognises only "*the* truth." The Church thus
keeps things in their proper order. Western societies, on the other hand, hold
tolerance to be of such primary importance that they enforce it by law.

Distinguish between the ideas we judge by (truth, beauty, and goodness), and the
ideas we live by (liberty, equality, and justice) -- Mortimer Adler.  We cannot
enjoy liberty, equality, and justice until we know something about truth, beauty,
and goodness.

The present situation in the West is not the tranquillity that arises from mutual
tolerance, but a "prison house of insincerity and hypocrisy known as political
correctness." -- Marcello Pera.

"Philosophy, because it is properly concerned with truth, goodness, beauty and
other fundamental verities, is indispensable in providing the basis for
civilisation and all the benefits that flow from it, including unity, civility,
justice, peace, art and science." -- Dr Donald DeMarco.

"Tolerance degenerates into intolerance when truth is subordinated to
tolerance. The rejection of truth does not make people tolerant."

Tolerance ...
  - is not the first principle of human conduct.
  - has never been the founding principle of any civilisation.
  - id used as a first principle, soon contradicts itself.
  - is not a first step, nor is it pro-active.
  - is acquiescence, a capitulation to something of which one neither approves
    nor disapproves.
  - presupposes moral neutrality.
  - is not a response nor an initiative.

As seen in the Spanish government's removal of the /offensive/ terms "father" and
"mother" from birth certificates (in favour of "Progenitor A and Progenitor B"),
what was originally intended to express /tolerance/ to married couples of the same
sex who have adopted children, has become intolerance towards the very words
"father" and "mother".

A society that does not put truth before tolerance (their proper order) allows
relativism to flourish. But relativism engenders insurmountable road blocks for
education, democracy, and the "implementation of natural law."

** Education

Practising relativism in education closes down the open discussion that must
take place to distinguish between right and wrong, truth and falsity, good and
evil.

Students entering Western universities today consider it axiomatic to believe
that "truth is relative." This makes them unwilling even to discuss their own
closedness.

"The phenomenon of not thinkiong is pandemic--both inside and outside of the
Church--and often goes unchallenged." People today *react* rather than think. They
react affitmatively to the opinions in social media; they repeat ideas that are
trndy, media-approved, and politically correct. And they call this bundle of
unexamined ideas a 'philosophy'. This 'philosophy' is *relativism*, in which truth
either does not exist or is unattainable.

To establish trusth we must engage in argument and dispute--and such engagement
is evidence of thinking. To avoid thinking because it is inconvenientor time
consuming is intellectually derelict and morally irresponsible--the simple fact
is that /truth matters./ "Thinking rightly leads to truth, and truth is the only
avenue to peace."

** Democracy

A good education is both a foundation and a safeguard of democracy--and a good
education does not neglect the importance of truth and virtue. If we abolish the
role of truth and virtue in education, our democracy and our society suffers.

Ethical relativism cannot be the basis for democracy because it yeilds to
totalitarian interests. It is inherently incapable of providing a basis for
unity nor is it an inspiration for decency.o

John Paul II told the United Nations that "democracy requires wisdon and virtue:
it stands or falls with the truths it embodies and promotes." Unfortunately,
vitue is not hereditary (Thomas Paine).

Western democracies are losing their democratic ideal, their affection for
virtue, particularly the subtle virtues needed for democracy, such as
selflessness, a desire for truth, a willingness to work, a keen sense of justice
and fair play, respect for marriage and family, and reverence for God.


John Courtney Murray (jesuit Father at the Second Vatican Council) said that men
[once] thought that democracy was inevitable; now they know that it is an
achievement, always precarious." Democracy is a living thing and as such, it
should be continually nourished and vigorously exercised. TYhe forst concern of
Western societies should be the health of their own democracy, and moral virtue
is the lifeblood of that health.

** Natural law

Certain goods are essential to democracy, according to Pope Benedict:
  - human dignity
  - human life
  - the institutin of the family
  - equity of the social order
Skepticism and ethical relativism have "clouded over" these essentials to the
extent that they threaten to undermine the foundations of democracy and a just
social order.


Benedict's appeal to natural law is not a theologically narrow appeal, but an
appeal that is philosophically broad.

Difference between the 'laws of nature' and 'natural law':
  - the formeroperate out of necessity.
  - the latter require the use of reason and the assent of the will.
