#+title:      The Eucharist is the body of Christ not Jesus
#+date:       [2023-07-12 Wed 15:37]
#+filetags:   :theology:
#+identifier: 20230712T153711

# The Eucharist is the body of Christ, not the body of Jesus

From [[https://www.americamagazine.org/faith/2023/07/11/eucharist-christ-245645?utm_source=piano&utm_medium=email&utm_campaign=2928&pnespid=s718CSJdOPoH2Kmdvy6uA4Cc4AupCIQsKbjjn7Vq9xNm95sK6KegUhM_ViIuj1PsYpBDlhJB][America Magazine]]

Comment by Ed Beckett:

#+BEGIN_QUOTE
When the bishops met for the Second Vatican Council, one of the key principles
they put forth is that Christ is present in the liturgy in four unique
ways. First, especially, in the Eucharist broken and shared, as well as in the
person of the minister, in the Word of God, and in the assembled people of
God. How many U.S. parishes are informed by a vibrant sense of a fourfold
presence of Christ operative in our Eucharistic celebration? How many pastors
work tirelessly toward such a sense of worship? And how often are our bishops
fostering such awareness?

Our impoverished Eucharistic worship due to the lack of a sense of active
participation and clear understanding is rooted in an excessively vertical lens
concerning our Eucharistic celebration. The vast majority of U.S. Catholics have
been formed into passivity when it comes to liturgy: it is an obligation, it is
centered on the priest, and it is tightly scheduled to assist with other
obligations (including the parish Mass schedule). The corrective, rooted in an
effective and efficacious catechesis concerning the fourfold presence of Christ
in our Eucharistic celebration, is hiding in plain sight. All that we need do is
remove the bushel basket and let the light shine.
#+END_QUOTE
